language: php
php:
  - '5.6'
services:
  - mysql
addons:
  hosts:
    - test.com
    - subdomain.test.com
before_install:
  # Install Zenphoto
  - mkdir zenphoto
  - "wget https://github.com/zenphoto/zenphoto/archive/zenphoto-1.4.13.tar.gz  -O ./zenphoto.tar.gz"
  - "tar -xvf ./zenphoto.tar.gz -C zenphoto --strip-components=1 --show-transformed "
  - cp zenphoto.cfg.php zenphoto/zp-data/
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS zenphoto;'"
  # - "mysql -e 'GRANT ALL PRIVILEGES ON zenphoto.* TO travis@localhost IDENTIFIED BY \'travis\';'"
  #- "mysql -e 'FLUSH PRIVILEGES;'"
  - "php -S localhost:8000 &" # Start php's internal webserver
  - sleep 3
  # Hit Zenphoto's setup page to set up clean URLs via Apache htaccess
  - "content=$(curl -L localhost:8000/zenphoto/zp-core/setup/index.php?copyhtaccess)"
  - echo $content
  # Hit Zenphoto's setup page to create database tables and other stuff
  - "content=$(curl -L localhost:8000/zenphoto/zp-core/setup/index.php?checked&create=zenphoto_options,zenphoto_albums,zenphoto_images,zenphoto_comments,zenphoto_administrators,zenphoto_admin_to_object,zenphoto_tags,zenphoto_obj_to_tag,zenphoto_captcha,zenphoto_pages,zenphoto_news2cat,zenphoto_news_categories,zenphoto_news,zenphoto_menu,zenphoto_plugin_storage,zenphoto_search_cache&mod_rewrite=ON)"
  - echo $content
  # Install a more recent version of Node.js's nvm
  - "wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh"
  - source ~/.nvm/nvm.sh
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] \&& \. "$NVM_DIR/nvm.sh"'  # This loads nvm
  # install Node.js v6
  - nvm install 6 
install: "npm install"
script: "npm test"