language: php
php:
  - '5.6'
services:
  - mysql
addons:
  hosts:
    - test.com
    - subdomain.test.com
before_install:
  - mkdir zenphoto
  - "wget https://github.com/zenphoto/zenphoto/archive/zenphoto-1.4.13.tar.gz  -O ./zenphoto.tar.gz"
  - "tar -xvf ./zenphoto.tar.gz -C zenphoto --strip-components=1 --show-transformed "
  - cp zenphoto.cfg.php zenphoto/zp-data/
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS zenphoto;'"
 # - "mysql -e 'GRANT ALL PRIVILEGES ON zenphoto.* TO travis@localhost IDENTIFIED BY \'travis\';'"
  #- "mysql -e 'FLUSH PRIVILEGES;'"
  - "php -S localhost:8000 &" # Start php's internal webserver
  - sleep 3
  - "content=$(curl -L localhost:8000/zenphoto/index.php)"
  - echo $content
  - "wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh"
  - source ~/.nvm/nvm.sh
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] \&& \. "$NVM_DIR/nvm.sh"'  # This loads nvm
  - nvm install 6 # install Node v6
install: "npm install"
script: "npm test"