language: php
php:
  - '5.6'
services:
  - mysql
addons:
  hosts:
    - test.com
    - subdomain.test.com
before_install:
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS test;'"
  - "wget https://github.com/zenphoto/zenphoto/archive/zenphoto-1.4.13.tar.gz  -O ./zenphoto.tar.gz"
  - mkdir zenphoto
  - "tar -xvf ./zenphoto.tar.gz -C ./zenphoto/"
  - "wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh"
  - source ~/.nvm/nvm.sh
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] \&& \. "$NVM_DIR/nvm.sh"'  # This loads nvm
  - nvm install 6 # install Node v6
  - node --version
  - echo $TRAVIS_BUILD_DIR
  - pwd
  - ls
  - "content=$(curl -L localhost:9000)"
  - echo $content
install: "npm install"
script: "npm test"